/* Generated by            cobc 1.1.0 */
/* Generated from          inventory.cbl */
/* Generated at            Feb 28 2018 03:43:58 EST */
/* OpenCOBOL build date    Feb 07 2016 10:28:13 */
/* OpenCOBOL package date  Feb 06 2009 10:30:55 CET */
/* Compile command         cobc -free -x -g -debug -ftraceall -o exe inventory.cbl */

/* Decimal structures */
static cob_decimal d0;
static cob_decimal d1;

/* File INV-FILE */
static cob_file		*h_INV_FILE = NULL;
static unsigned char	h_INV_FILE_status[4];
/* File CUST-FILE */
static cob_file		*h_CUST_FILE = NULL;
static unsigned char	h_CUST_FILE_status[4];
/* File TRANS-FILE */
static cob_file		*h_TRANS_FILE = NULL;
static unsigned char	h_TRANS_FILE_status[4];
/* File ERROR-FILE */
static cob_file		*h_ERROR_FILE = NULL;
static unsigned char	h_ERROR_FILE_status[4];
/* File TRANS-OUTPUT-FILE */
static cob_file		*h_TRANS_OUTPUT_FILE = NULL;
static unsigned char	h_TRANS_OUTPUT_FILE_status[4];
/* File INV-ORDER-FILE */
static cob_file		*h_INV_ORDER_FILE = NULL;
static unsigned char	h_INV_ORDER_FILE_status[4];

/* Define perform frame stack */

struct cob_frame	*frame_overflow;
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];

int		i1;

/* Local cob_field items */
cob_field	f0;

