/* Generated by            cobc 1.1.0 */
/* Generated from          inventory.cbl */
/* Generated at            Feb 28 2018 03:43:58 EST */
/* OpenCOBOL build date    Feb 07 2016 10:28:13 */
/* OpenCOBOL package date  Feb 06 2009 10:30:55 CET */
/* Compile command         cobc -free -x -g -debug -ftraceall -o exe inventory.cbl */

#define  __USE_STRING_INLINES 1
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <libcob.h>

#define COB_SOURCE_FILE		"inventory.cbl"
#define COB_PACKAGE_VERSION	"1.1"
#define COB_PATCH_LEVEL		0

/* Global variables */
#include "inventory.c.h"

static void
cob_decimal_set_int (cob_decimal *d, const int n)
{
	mpz_set_si (d->value, n);
	d->scale = 0;
}

static void
cob_decimal_set_uint (cob_decimal *d, const unsigned int n)
{
	mpz_set_ui (d->value, n);
	d->scale = 0;
}

/* Function prototypes */

int NKU_20CSC407_20OLDIE_20ASSIGNMENT ();
static int NKU_20CSC407_20OLDIE_20ASSIGNMENT_ (const int);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (NKU_20CSC407_20OLDIE_20ASSIGNMENT ());
}

/* Functions */

int
NKU_20CSC407_20OLDIE_20ASSIGNMENT ()
{
  return NKU_20CSC407_20OLDIE_20ASSIGNMENT_ (0);
}

static int
NKU_20CSC407_20OLDIE_20ASSIGNMENT_ (const int entry)
{
  /* Local variables */
  #include "inventory.c.l.h"

  static int initialized = 0;
  static cob_field *cob_user_parameters[COB_MAX_FIELD_PARAMS];
  static struct cob_module module = { NULL, NULL, NULL, NULL, cob_user_parameters, 0, '.', '$', ',', 1, 1, 1, 0 };

  /* Start of function code */

  /* CANCEL callback handling */
  if (unlikely(entry < 0)) {
  	if (!initialized) {
  		return 0;
  	}
  	cob_close (h_INV_FILE, 0, NULL);
  	cob_close (h_CUST_FILE, 0, NULL);
  	cob_close (h_TRANS_FILE, 0, NULL);
  	cob_close (h_ERROR_FILE, 0, NULL);
  	cob_close (h_TRANS_OUTPUT_FILE, 0, NULL);
  	cob_close (h_INV_ORDER_FILE, 0, NULL);
  	mpz_clear (d0.value);
  	d0.scale = 0;
  	mpz_clear (d1.value);
  	d1.scale = 0;
  	initialized = 0;
  	return 0;
  }

  /* Initialize frame stack */
  frame_ptr = &frame_stack[0];
  frame_ptr->perform_through = 0;
  frame_overflow = &frame_stack[COB_STACK_SIZE - 1];

  /* Push module stack */
  module.next = cob_current_module;
  cob_current_module = &module;

  /* Initialize program */
  if (unlikely(initialized == 0))
    {
      if (!cob_initialized) {
        cob_fatal_error (COB_FERROR_INITIALIZED);
      }
      cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
      /* Initialize decimal numbers */
      cob_decimal_init (&d0);
      cob_decimal_init (&d1);

      (*(int *) (b_1)) = 0;
      (*(int *) (b_71)) = 1;
      (*(int *) (b_79)) = 1;
      *(unsigned char *) (b_63) = 78;
      *(unsigned char *) (b_63 + 1) = 78;
      *(unsigned char *) (b_63 + 2) = 78;
      *(unsigned char *) (b_63 + 3) = 78;
      *(unsigned char *) (b_63 + 4) = 78;
      for (i1 = 1; i1 <= 24; i1++)
        {
          memset (b_69 + 39 * (i1 - 1), 32, 31);
          memset (b_69 + 31 + 39 * (i1 - 1), 48, 8);
        }
      for (i1 = 1; i1 <= 10; i1++)
        {
          memset (b_77 + 81 * (i1 - 1), 48, 5);
          memset (b_77 + 5 + 81 * (i1 - 1), 32, 71);
          memset (b_77 + 76 + 81 * (i1 - 1), 48, 5);
        }
      memset (b_86, 48, 5);
      memset (b_86 + 5, 48, 5);

      if (!h_INV_FILE)
      {
        h_INV_FILE = cob_malloc (sizeof(cob_file));
      }
      h_INV_FILE->select_name = (const char *)"INV-FILE";
      h_INV_FILE->file_status = h_INV_FILE_status;
      memset (h_INV_FILE_status, '0', 2);
      h_INV_FILE->assign = &c_1;
      h_INV_FILE->record = &f_14;
      h_INV_FILE->record_size = NULL;
      h_INV_FILE->record_min = 0;
      h_INV_FILE->record_max = 55;
      h_INV_FILE->nkeys = 0;
      h_INV_FILE->keys = NULL;
      h_INV_FILE->file = NULL;
      h_INV_FILE->organization = 1;
      h_INV_FILE->access_mode = 1;
      h_INV_FILE->lock_mode = 0;
      h_INV_FILE->open_mode = 0;
      h_INV_FILE->flag_optional = 0;
      h_INV_FILE->last_open_mode = 0;
      h_INV_FILE->special = 0;
      h_INV_FILE->flag_nonexistent = 0;
      h_INV_FILE->flag_end_of_file = 0;
      h_INV_FILE->flag_begin_of_file = 0;
      h_INV_FILE->flag_first_read = 0;
      h_INV_FILE->flag_read_done = 0;
      h_INV_FILE->flag_select_features = 0;
      h_INV_FILE->flag_needs_nl = 0;
      h_INV_FILE->flag_needs_top = 0;
      h_INV_FILE->file_version = 0;
      if (!h_CUST_FILE)
      {
        h_CUST_FILE = cob_malloc (sizeof(cob_file));
      }
      h_CUST_FILE->select_name = (const char *)"CUST-FILE";
      h_CUST_FILE->file_status = h_CUST_FILE_status;
      memset (h_CUST_FILE_status, '0', 2);
      h_CUST_FILE->assign = &c_2;
      h_CUST_FILE->record = &f_23;
      h_CUST_FILE->record_size = NULL;
      h_CUST_FILE->record_min = 0;
      h_CUST_FILE->record_max = 87;
      h_CUST_FILE->nkeys = 0;
      h_CUST_FILE->keys = NULL;
      h_CUST_FILE->file = NULL;
      h_CUST_FILE->organization = 1;
      h_CUST_FILE->access_mode = 1;
      h_CUST_FILE->lock_mode = 0;
      h_CUST_FILE->open_mode = 0;
      h_CUST_FILE->flag_optional = 0;
      h_CUST_FILE->last_open_mode = 0;
      h_CUST_FILE->special = 0;
      h_CUST_FILE->flag_nonexistent = 0;
      h_CUST_FILE->flag_end_of_file = 0;
      h_CUST_FILE->flag_begin_of_file = 0;
      h_CUST_FILE->flag_first_read = 0;
      h_CUST_FILE->flag_read_done = 0;
      h_CUST_FILE->flag_select_features = 0;
      h_CUST_FILE->flag_needs_nl = 0;
      h_CUST_FILE->flag_needs_top = 0;
      h_CUST_FILE->file_version = 0;
      if (!h_TRANS_FILE)
      {
        h_TRANS_FILE = cob_malloc (sizeof(cob_file));
      }
      h_TRANS_FILE->select_name = (const char *)"TRANS-FILE";
      h_TRANS_FILE->file_status = h_TRANS_FILE_status;
      memset (h_TRANS_FILE_status, '0', 2);
      h_TRANS_FILE->assign = &c_3;
      h_TRANS_FILE->record = &f_32;
      h_TRANS_FILE->record_size = NULL;
      h_TRANS_FILE->record_min = 0;
      h_TRANS_FILE->record_max = 29;
      h_TRANS_FILE->nkeys = 0;
      h_TRANS_FILE->keys = NULL;
      h_TRANS_FILE->file = NULL;
      h_TRANS_FILE->organization = 1;
      h_TRANS_FILE->access_mode = 1;
      h_TRANS_FILE->lock_mode = 0;
      h_TRANS_FILE->open_mode = 0;
      h_TRANS_FILE->flag_optional = 0;
      h_TRANS_FILE->last_open_mode = 0;
      h_TRANS_FILE->special = 0;
      h_TRANS_FILE->flag_nonexistent = 0;
      h_TRANS_FILE->flag_end_of_file = 0;
      h_TRANS_FILE->flag_begin_of_file = 0;
      h_TRANS_FILE->flag_first_read = 0;
      h_TRANS_FILE->flag_read_done = 0;
      h_TRANS_FILE->flag_select_features = 0;
      h_TRANS_FILE->flag_needs_nl = 0;
      h_TRANS_FILE->flag_needs_top = 0;
      h_TRANS_FILE->file_version = 0;
      if (!h_ERROR_FILE)
      {
        h_ERROR_FILE = cob_malloc (sizeof(cob_file));
      }
      h_ERROR_FILE->select_name = (const char *)"ERROR-FILE";
      h_ERROR_FILE->file_status = h_ERROR_FILE_status;
      memset (h_ERROR_FILE_status, '0', 2);
      h_ERROR_FILE->assign = &c_4;
      h_ERROR_FILE->record = &f_41;
      h_ERROR_FILE->record_size = NULL;
      h_ERROR_FILE->record_min = 0;
      h_ERROR_FILE->record_max = 52;
      h_ERROR_FILE->nkeys = 0;
      h_ERROR_FILE->keys = NULL;
      h_ERROR_FILE->file = NULL;
      h_ERROR_FILE->organization = 1;
      h_ERROR_FILE->access_mode = 1;
      h_ERROR_FILE->lock_mode = 0;
      h_ERROR_FILE->open_mode = 0;
      h_ERROR_FILE->flag_optional = 0;
      h_ERROR_FILE->last_open_mode = 0;
      h_ERROR_FILE->special = 0;
      h_ERROR_FILE->flag_nonexistent = 0;
      h_ERROR_FILE->flag_end_of_file = 0;
      h_ERROR_FILE->flag_begin_of_file = 0;
      h_ERROR_FILE->flag_first_read = 0;
      h_ERROR_FILE->flag_read_done = 0;
      h_ERROR_FILE->flag_select_features = 0;
      h_ERROR_FILE->flag_needs_nl = 0;
      h_ERROR_FILE->flag_needs_top = 0;
      h_ERROR_FILE->file_version = 0;
      if (!h_TRANS_OUTPUT_FILE)
      {
        h_TRANS_OUTPUT_FILE = cob_malloc (sizeof(cob_file));
      }
      h_TRANS_OUTPUT_FILE->select_name = (const char *)"TRANS-OUTPUT-FILE";
      h_TRANS_OUTPUT_FILE->file_status = h_TRANS_OUTPUT_FILE_status;
      memset (h_TRANS_OUTPUT_FILE_status, '0', 2);
      h_TRANS_OUTPUT_FILE->assign = &c_5;
      h_TRANS_OUTPUT_FILE->record = &f_57;
      h_TRANS_OUTPUT_FILE->record_size = NULL;
      h_TRANS_OUTPUT_FILE->record_min = 0;
      h_TRANS_OUTPUT_FILE->record_max = 142;
      h_TRANS_OUTPUT_FILE->nkeys = 0;
      h_TRANS_OUTPUT_FILE->keys = NULL;
      h_TRANS_OUTPUT_FILE->file = NULL;
      h_TRANS_OUTPUT_FILE->organization = 1;
      h_TRANS_OUTPUT_FILE->access_mode = 1;
      h_TRANS_OUTPUT_FILE->lock_mode = 0;
      h_TRANS_OUTPUT_FILE->open_mode = 0;
      h_TRANS_OUTPUT_FILE->flag_optional = 0;
      h_TRANS_OUTPUT_FILE->last_open_mode = 0;
      h_TRANS_OUTPUT_FILE->special = 0;
      h_TRANS_OUTPUT_FILE->flag_nonexistent = 0;
      h_TRANS_OUTPUT_FILE->flag_end_of_file = 0;
      h_TRANS_OUTPUT_FILE->flag_begin_of_file = 0;
      h_TRANS_OUTPUT_FILE->flag_first_read = 0;
      h_TRANS_OUTPUT_FILE->flag_read_done = 0;
      h_TRANS_OUTPUT_FILE->flag_select_features = 0;
      h_TRANS_OUTPUT_FILE->flag_needs_nl = 0;
      h_TRANS_OUTPUT_FILE->flag_needs_top = 0;
      h_TRANS_OUTPUT_FILE->file_version = 0;
      if (!h_INV_ORDER_FILE)
      {
        h_INV_ORDER_FILE = cob_malloc (sizeof(cob_file));
      }
      h_INV_ORDER_FILE->select_name = (const char *)"INV-ORDER-FILE";
      h_INV_ORDER_FILE->file_status = h_INV_ORDER_FILE_status;
      memset (h_INV_ORDER_FILE_status, '0', 2);
      h_INV_ORDER_FILE->assign = &c_6;
      h_INV_ORDER_FILE->record = &f_62;
      h_INV_ORDER_FILE->record_size = NULL;
      h_INV_ORDER_FILE->record_min = 0;
      h_INV_ORDER_FILE->record_max = 14;
      h_INV_ORDER_FILE->nkeys = 0;
      h_INV_ORDER_FILE->keys = NULL;
      h_INV_ORDER_FILE->file = NULL;
      h_INV_ORDER_FILE->organization = 1;
      h_INV_ORDER_FILE->access_mode = 1;
      h_INV_ORDER_FILE->lock_mode = 0;
      h_INV_ORDER_FILE->open_mode = 0;
      h_INV_ORDER_FILE->flag_optional = 0;
      h_INV_ORDER_FILE->last_open_mode = 0;
      h_INV_ORDER_FILE->special = 0;
      h_INV_ORDER_FILE->flag_nonexistent = 0;
      h_INV_ORDER_FILE->flag_end_of_file = 0;
      h_INV_ORDER_FILE->flag_begin_of_file = 0;
      h_INV_ORDER_FILE->flag_first_read = 0;
      h_INV_ORDER_FILE->flag_read_done = 0;
      h_INV_ORDER_FILE->flag_select_features = 0;
      h_INV_ORDER_FILE->flag_needs_nl = 0;
      h_INV_ORDER_FILE->flag_needs_top = 0;
      h_INV_ORDER_FILE->file_version = 0;

      initialized = 1;
    }

  cob_save_call_params = cob_call_params;

  cob_ready_trace ();

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Entry NKU CSC407 OLDIE ASSIGNMENT */

  l_2:;
  fputs ("PROGRAM-ID: NKU CSC407 OLDIE ASSIGNMENT: ENTRY NKU CSC407 OLDIE ASSIGNMENT\n", stderr);
  fflush (stderr);

  /* MAIN SECTION */
  fputs ("PROGRAM-ID: NKU CSC407 OLDIE ASSIGNMENT: MAIN SECTION\n", stderr);
  fflush (stderr);

  /* 000-FULFILL-ORDERS */

  fputs ("PROGRAM-ID: NKU CSC407 OLDIE ASSIGNMENT: 000-FULFILL-ORDERS\n", stderr);
  fflush (stderr);
  /* inventory.cbl:135: PERFORM */
  cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 135, "MAIN SECTION", "000-FULFILL-ORDERS", "PERFORM");
  {
    /* PERFORM 010-IMPORT-INVENTORY */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 5;
    frame_ptr->return_address = &&l_18;
    goto l_5;
    l_18:
    frame_ptr--;
  }
  /* inventory.cbl:136: PERFORM */
  cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 136, "MAIN SECTION", "000-FULFILL-ORDERS", "PERFORM");
  {
    /* PERFORM 020-IMPORT-CUSTOMER */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 6;
    frame_ptr->return_address = &&l_19;
    goto l_6;
    l_19:
    frame_ptr--;
  }
  /* inventory.cbl:137: PERFORM */
  cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 137, "MAIN SECTION", "000-FULFILL-ORDERS", "PERFORM");
  {
    /* PERFORM 030-READ-TRANSACTIONS */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 7;
    frame_ptr->return_address = &&l_20;
    goto l_7;
    l_20:
    frame_ptr--;
  }
  /* inventory.cbl:138: STOP */
  cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 138, "MAIN SECTION", "000-FULFILL-ORDERS", "STOP");
  {
    cob_stop_run ((*(int *) (b_1)));
  }

  /* 010-IMPORT-INVENTORY */

  l_5:;
  fputs ("PROGRAM-ID: NKU CSC407 OLDIE ASSIGNMENT: 010-IMPORT-INVENTORY\n", stderr);
  fflush (stderr);
  /* inventory.cbl:141: OPEN */
  cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 141, "MAIN SECTION", "010-IMPORT-INVENTORY", "OPEN");
  {
    cob_exception_code = 0;
    {
      cob_open (h_INV_FILE, 1, 0, NULL);
    }
    if (unlikely(cob_exception_code != 0))
      {
        /* PERFORM Default Error Handler */
        frame_ptr++;
        if (unlikely(frame_ptr == frame_overflow))
            cob_fatal_error (COB_FERROR_STACK);
        frame_ptr->perform_through = 1;
        frame_ptr->return_address = &&l_21;
        goto l_1;
        l_21:
        frame_ptr--;
      }
  }
  /* inventory.cbl:142: PERFORM */
  cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 142, "MAIN SECTION", "010-IMPORT-INVENTORY", "PERFORM");
  {
    while (1)
      {
        if (((int)(int)(*(b_63) - 89) == 0))
          break;
        {
          /* inventory.cbl:143: READ */
          cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 143, "MAIN SECTION", "010-IMPORT-INVENTORY", "READ");
          cob_exception_code = 0;
          {
            cob_read (h_INV_FILE, 0, NULL, 1);
          }
          if (unlikely(cob_exception_code != 0))
            {
              if (cob_exception_code == 0x0501)
                {
                  {
                    /* inventory.cbl:145: MOVE */
                    cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 145, "MAIN SECTION", "010-IMPORT-INVENTORY", "MOVE");
                    {
                      *(b_63) = 89;
                    }
                  }
                }
              else
                {
                  /* PERFORM Default Error Handler */
                  frame_ptr++;
                  if (unlikely(frame_ptr == frame_overflow))
                      cob_fatal_error (COB_FERROR_STACK);
                  frame_ptr->perform_through = 1;
                  frame_ptr->return_address = &&l_22;
                  goto l_1;
                  l_22:
                  frame_ptr--;
                }
            }
          else
            {
              memcpy (b_14, b_14, 55);
              {
                /* inventory.cbl:147: ADD */
                cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 147, "MAIN SECTION", "010-IMPORT-INVENTORY", "ADD");
                {
                  cob_check_numeric (&f_87, "INV-NUM-IN");
                  cob_add (&f_87, &c_7, 2);
                }
                /* inventory.cbl:148: MOVE */
                cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 148, "MAIN SECTION", "010-IMPORT-INVENTORY", "MOVE");
                {
                  cob_move (&f_6,                    ({
                  cob_check_subscript (cob_get_int (&f_87), 1, 24, "WS-INV-ITEM-NO");
(f0.size = 6, f0.data = b_69 + 39 * (cob_get_int (&f_87) - 1), f0.attr = &a_1, &f0); }));
                }
                /* inventory.cbl:149: MOVE */
                cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 149, "MAIN SECTION", "010-IMPORT-INVENTORY", "MOVE");
                {
                  cob_move (&f_8,                    ({
                  cob_check_subscript (cob_get_int (&f_87), 1, 24, "WS-INV-ITEM-NAME");
(f0.size = 25, f0.data = b_69 + 6 + 39 * (cob_get_int (&f_87) - 1), f0.attr = &a_1, &f0); }));
                }
                /* inventory.cbl:150: MOVE */
                cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 150, "MAIN SECTION", "010-IMPORT-INVENTORY", "MOVE");
                {
                  cob_move (&f_9,                    ({
                  cob_check_subscript (cob_get_int (&f_87), 1, 24, "WS-INV-QTY");
(f0.size = 2, f0.data = b_69 + 31 + 39 * (cob_get_int (&f_87) - 1), f0.attr = &a_4, &f0); }));
                }
                /* inventory.cbl:151: MOVE */
                cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 151, "MAIN SECTION", "010-IMPORT-INVENTORY", "MOVE");
                {
                  cob_move (&f_11,                    ({
                  cob_check_subscript (cob_get_int (&f_87), 1, 24, "WS-INV-REORDER-PT");
(f0.size = 2, f0.data = b_69 + 33 + 39 * (cob_get_int (&f_87) - 1), f0.attr = &a_4, &f0); }));
                }
                /* inventory.cbl:152: MOVE */
                cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 152, "MAIN SECTION", "010-IMPORT-INVENTORY", "MOVE");
                {
                  cob_move (&f_13,                    ({
                  cob_check_subscript (cob_get_int (&f_87), 1, 24, "WS-INV-PRICE");
(f0.size = 4, f0.data = b_69 + 35 + 39 * (cob_get_int (&f_87) - 1), f0.attr = &a_6, &f0); }));
                }
              }
            }
        }
      }
  }
  /* inventory.cbl:155: CLOSE */
  cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 155, "MAIN SECTION", "010-IMPORT-INVENTORY", "CLOSE");
  {
    cob_exception_code = 0;
    {
      cob_close (h_INV_FILE, 0, NULL);
    }
    if (unlikely(cob_exception_code != 0))
      {
        /* PERFORM Default Error Handler */
        frame_ptr++;
        if (unlikely(frame_ptr == frame_overflow))
            cob_fatal_error (COB_FERROR_STACK);
        frame_ptr->perform_through = 1;
        frame_ptr->return_address = &&l_23;
        goto l_1;
        l_23:
        frame_ptr--;
      }
  }

  if (frame_ptr->perform_through == 5)
    goto *frame_ptr->return_address;

  /* 020-IMPORT-CUSTOMER */

  l_6:;
  fputs ("PROGRAM-ID: NKU CSC407 OLDIE ASSIGNMENT: 020-IMPORT-CUSTOMER\n", stderr);
  fflush (stderr);
  /* inventory.cbl:158: OPEN */
  cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 158, "MAIN SECTION", "020-IMPORT-CUSTOMER", "OPEN");
  {
    cob_exception_code = 0;
    {
      cob_open (h_CUST_FILE, 1, 0, NULL);
    }
    if (unlikely(cob_exception_code != 0))
      {
        /* PERFORM Default Error Handler */
        frame_ptr++;
        if (unlikely(frame_ptr == frame_overflow))
            cob_fatal_error (COB_FERROR_STACK);
        frame_ptr->perform_through = 1;
        frame_ptr->return_address = &&l_24;
        goto l_1;
        l_24:
        frame_ptr--;
      }
  }
  /* inventory.cbl:159: PERFORM */
  cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 159, "MAIN SECTION", "020-IMPORT-CUSTOMER", "PERFORM");
  {
    while (1)
      {
        if (((int)(int)(*(b_63 + 1) - 89) == 0))
          break;
        {
          /* inventory.cbl:160: READ */
          cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 160, "MAIN SECTION", "020-IMPORT-CUSTOMER", "READ");
          cob_exception_code = 0;
          {
            cob_read (h_CUST_FILE, 0, NULL, 1);
          }
          if (unlikely(cob_exception_code != 0))
            {
              if (cob_exception_code == 0x0501)
                {
                  {
                    /* inventory.cbl:162: MOVE */
                    cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 162, "MAIN SECTION", "020-IMPORT-CUSTOMER", "MOVE");
                    {
                      *(b_63 + 1) = 89;
                    }
                  }
                }
              else
                {
                  /* PERFORM Default Error Handler */
                  frame_ptr++;
                  if (unlikely(frame_ptr == frame_overflow))
                      cob_fatal_error (COB_FERROR_STACK);
                  frame_ptr->perform_through = 1;
                  frame_ptr->return_address = &&l_25;
                  goto l_1;
                  l_25:
                  frame_ptr--;
                }
            }
          else
            {
              memcpy (b_23, b_23, 87);
              {
                /* inventory.cbl:164: ADD */
                cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 164, "MAIN SECTION", "020-IMPORT-CUSTOMER", "ADD");
                {
                  cob_check_numeric (&f_88, "CUST-NUM-IN");
                  cob_add (&f_88, &c_7, 2);
                }
                /* inventory.cbl:165: MOVE */
                cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 165, "MAIN SECTION", "020-IMPORT-CUSTOMER", "MOVE");
                {
                  cob_move (&f_16,                    ({
                  cob_check_subscript (cob_get_int (&f_88), 1, 10, "WS-CUST-NO");
(f0.size = 5, f0.data = b_77 + 81 * (cob_get_int (&f_88) - 1), f0.attr = &a_7, &f0); }));
                }
                /* inventory.cbl:166: MOVE */
                cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 166, "MAIN SECTION", "020-IMPORT-CUSTOMER", "MOVE");
                {
                  cob_move (&f_18,                    ({
                  cob_check_subscript (cob_get_int (&f_88), 1, 10, "WS-CUST-NAME");
(f0.size = 23, f0.data = b_77 + 5 + 81 * (cob_get_int (&f_88) - 1), f0.attr = &a_1, &f0); }));
                }
                /* inventory.cbl:167: MOVE */
                cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 167, "MAIN SECTION", "020-IMPORT-CUSTOMER", "MOVE");
                {
                  cob_move (&f_19,                    ({
                  cob_check_subscript (cob_get_int (&f_88), 1, 10, "WS-CUST-STREET");
(f0.size = 23, f0.data = b_77 + 28 + 81 * (cob_get_int (&f_88) - 1), f0.attr = &a_1, &f0); }));
                }
                /* inventory.cbl:168: MOVE */
                cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 168, "MAIN SECTION", "020-IMPORT-CUSTOMER", "MOVE");
                {
                  cob_move (&f_20,                    ({
                  cob_check_subscript (cob_get_int (&f_88), 1, 10, "WS-CUST-CITY");
(f0.size = 13, f0.data = b_77 + 51 + 81 * (cob_get_int (&f_88) - 1), f0.attr = &a_1, &f0); }));
                }
                /* inventory.cbl:169: MOVE */
                cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 169, "MAIN SECTION", "020-IMPORT-CUSTOMER", "MOVE");
                {
                  cob_move (&f_21,                    ({
                  cob_check_subscript (cob_get_int (&f_88), 1, 10, "WS-CUST-REGION");
(f0.size = 12, f0.data = b_77 + 64 + 81 * (cob_get_int (&f_88) - 1), f0.attr = &a_1, &f0); }));
                }
                /* inventory.cbl:170: MOVE */
                cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 170, "MAIN SECTION", "020-IMPORT-CUSTOMER", "MOVE");
                {
                  cob_move (&f_22,                    ({
                  cob_check_subscript (cob_get_int (&f_88), 1, 10, "WS-CUST-PAST-DUE");
(f0.size = 5, f0.data = b_77 + 76 + 81 * (cob_get_int (&f_88) - 1), f0.attr = &a_9, &f0); }));
                }
              }
            }
        }
      }
  }
  /* inventory.cbl:173: CLOSE */
  cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 173, "MAIN SECTION", "020-IMPORT-CUSTOMER", "CLOSE");
  {
    cob_exception_code = 0;
    {
      cob_close (h_CUST_FILE, 0, NULL);
    }
    if (unlikely(cob_exception_code != 0))
      {
        /* PERFORM Default Error Handler */
        frame_ptr++;
        if (unlikely(frame_ptr == frame_overflow))
            cob_fatal_error (COB_FERROR_STACK);
        frame_ptr->perform_through = 1;
        frame_ptr->return_address = &&l_26;
        goto l_1;
        l_26:
        frame_ptr--;
      }
  }

  if (frame_ptr->perform_through == 6)
    goto *frame_ptr->return_address;

  /* 030-READ-TRANSACTIONS */

  l_7:;
  fputs ("PROGRAM-ID: NKU CSC407 OLDIE ASSIGNMENT: 030-READ-TRANSACTIONS\n", stderr);
  fflush (stderr);
  /* inventory.cbl:176: OPEN */
  cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 176, "MAIN SECTION", "030-READ-TRANSACTIONS", "OPEN");
  {
    cob_exception_code = 0;
    {
      cob_open (h_TRANS_FILE, 1, 0, NULL);
    }
    if (unlikely(cob_exception_code != 0))
      {
        /* PERFORM Default Error Handler */
        frame_ptr++;
        if (unlikely(frame_ptr == frame_overflow))
            cob_fatal_error (COB_FERROR_STACK);
        frame_ptr->perform_through = 1;
        frame_ptr->return_address = &&l_27;
        goto l_1;
        l_27:
        frame_ptr--;
      }
  }
  /* inventory.cbl:177: OPEN */
  cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 177, "MAIN SECTION", "030-READ-TRANSACTIONS", "OPEN");
  {
    cob_exception_code = 0;
    {
      cob_open (h_ERROR_FILE, 2, 1, NULL);
    }
    if (unlikely(cob_exception_code != 0))
      {
        /* PERFORM Default Error Handler */
        frame_ptr++;
        if (unlikely(frame_ptr == frame_overflow))
            cob_fatal_error (COB_FERROR_STACK);
        frame_ptr->perform_through = 1;
        frame_ptr->return_address = &&l_28;
        goto l_1;
        l_28:
        frame_ptr--;
      }
  }
  /* inventory.cbl:178: OPEN */
  cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 178, "MAIN SECTION", "030-READ-TRANSACTIONS", "OPEN");
  {
    cob_exception_code = 0;
    {
      cob_open (h_INV_ORDER_FILE, 2, 1, NULL);
    }
    if (unlikely(cob_exception_code != 0))
      {
        /* PERFORM Default Error Handler */
        frame_ptr++;
        if (unlikely(frame_ptr == frame_overflow))
            cob_fatal_error (COB_FERROR_STACK);
        frame_ptr->perform_through = 1;
        frame_ptr->return_address = &&l_29;
        goto l_1;
        l_29:
        frame_ptr--;
      }
  }
  /* inventory.cbl:179: OPEN */
  cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 179, "MAIN SECTION", "030-READ-TRANSACTIONS", "OPEN");
  {
    cob_exception_code = 0;
    {
      cob_open (h_TRANS_OUTPUT_FILE, 2, 1, NULL);
    }
    if (unlikely(cob_exception_code != 0))
      {
        /* PERFORM Default Error Handler */
        frame_ptr++;
        if (unlikely(frame_ptr == frame_overflow))
            cob_fatal_error (COB_FERROR_STACK);
        frame_ptr->perform_through = 1;
        frame_ptr->return_address = &&l_30;
        goto l_1;
        l_30:
        frame_ptr--;
      }
  }
  /* inventory.cbl:181: PERFORM */
  cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 181, "MAIN SECTION", "030-READ-TRANSACTIONS", "PERFORM");
  {
    while (1)
      {
        if (((int)(int)(*(b_63 + 2) - 89) == 0))
          break;
        {
          /* inventory.cbl:182: READ */
          cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 182, "MAIN SECTION", "030-READ-TRANSACTIONS", "READ");
          cob_exception_code = 0;
          {
            cob_read (h_TRANS_FILE, 0, NULL, 1);
          }
          if (unlikely(cob_exception_code != 0))
            {
              if (cob_exception_code == 0x0501)
                {
                  {
                    /* inventory.cbl:184: MOVE */
                    cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 184, "MAIN SECTION", "030-READ-TRANSACTIONS", "MOVE");
                    {
                      *(b_63 + 2) = 89;
                    }
                  }
                }
              else
                {
                  /* PERFORM Default Error Handler */
                  frame_ptr++;
                  if (unlikely(frame_ptr == frame_overflow))
                      cob_fatal_error (COB_FERROR_STACK);
                  frame_ptr->perform_through = 1;
                  frame_ptr->return_address = &&l_31;
                  goto l_1;
                  l_31:
                  frame_ptr--;
                }
            }
          else
            {
              memcpy (b_32, b_32, 29);
              {
                /* inventory.cbl:186: PERFORM */
                cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 186, "MAIN SECTION", "030-READ-TRANSACTIONS", "PERFORM");
                {
                  /* PERFORM 031-PROCESS-TRANSACTION */
                  frame_ptr++;
                  if (unlikely(frame_ptr == frame_overflow))
                      cob_fatal_error (COB_FERROR_STACK);
                  frame_ptr->perform_through = 8;
                  frame_ptr->return_address = &&l_32;
                  goto l_8;
                  l_32:
                  frame_ptr--;
                }
              }
            }
        }
      }
  }
  /* inventory.cbl:189: CLOSE */
  cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 189, "MAIN SECTION", "030-READ-TRANSACTIONS", "CLOSE");
  {
    cob_exception_code = 0;
    {
      cob_close (h_TRANS_FILE, 0, NULL);
    }
    if (unlikely(cob_exception_code != 0))
      {
        /* PERFORM Default Error Handler */
        frame_ptr++;
        if (unlikely(frame_ptr == frame_overflow))
            cob_fatal_error (COB_FERROR_STACK);
        frame_ptr->perform_through = 1;
        frame_ptr->return_address = &&l_33;
        goto l_1;
        l_33:
        frame_ptr--;
      }
  }
  /* inventory.cbl:190: CLOSE */
  cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 190, "MAIN SECTION", "030-READ-TRANSACTIONS", "CLOSE");
  {
    cob_exception_code = 0;
    {
      cob_close (h_ERROR_FILE, 0, NULL);
    }
    if (unlikely(cob_exception_code != 0))
      {
        /* PERFORM Default Error Handler */
        frame_ptr++;
        if (unlikely(frame_ptr == frame_overflow))
            cob_fatal_error (COB_FERROR_STACK);
        frame_ptr->perform_through = 1;
        frame_ptr->return_address = &&l_34;
        goto l_1;
        l_34:
        frame_ptr--;
      }
  }
  /* inventory.cbl:191: CLOSE */
  cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 191, "MAIN SECTION", "030-READ-TRANSACTIONS", "CLOSE");
  {
    cob_exception_code = 0;
    {
      cob_close (h_INV_ORDER_FILE, 0, NULL);
    }
    if (unlikely(cob_exception_code != 0))
      {
        /* PERFORM Default Error Handler */
        frame_ptr++;
        if (unlikely(frame_ptr == frame_overflow))
            cob_fatal_error (COB_FERROR_STACK);
        frame_ptr->perform_through = 1;
        frame_ptr->return_address = &&l_35;
        goto l_1;
        l_35:
        frame_ptr--;
      }
  }
  /* inventory.cbl:192: CLOSE */
  cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 192, "MAIN SECTION", "030-READ-TRANSACTIONS", "CLOSE");
  {
    cob_exception_code = 0;
    {
      cob_close (h_TRANS_OUTPUT_FILE, 0, NULL);
    }
    if (unlikely(cob_exception_code != 0))
      {
        /* PERFORM Default Error Handler */
        frame_ptr++;
        if (unlikely(frame_ptr == frame_overflow))
            cob_fatal_error (COB_FERROR_STACK);
        frame_ptr->perform_through = 1;
        frame_ptr->return_address = &&l_36;
        goto l_1;
        l_36:
        frame_ptr--;
      }
  }

  if (frame_ptr->perform_through == 7)
    goto *frame_ptr->return_address;

  /* 031-PROCESS-TRANSACTION */

  l_8:;
  fputs ("PROGRAM-ID: NKU CSC407 OLDIE ASSIGNMENT: 031-PROCESS-TRANSACTION\n", stderr);
  fflush (stderr);
  /* inventory.cbl:195: MOVE */
  cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 195, "MAIN SECTION", "031-PROCESS-TRANSACTION", "MOVE");
  {
    memset (b_41, 32, 52);
  }
  /* inventory.cbl:196: PERFORM */
  cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 196, "MAIN SECTION", "031-PROCESS-TRANSACTION", "PERFORM");
  {
    /* PERFORM 032-CUST-NO-SEARCH */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 9;
    frame_ptr->return_address = &&l_37;
    goto l_9;
    l_37:
    frame_ptr--;
  }
  /* inventory.cbl:197: IF */
  cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 197, "MAIN SECTION", "031-PROCESS-TRANSACTION", "IF");
  {
    if (((int)(int)(*(b_63 + 3) - 78) == 0))
      {
        /* inventory.cbl:198: MOVE */
        cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 198, "MAIN SECTION", "031-PROCESS-TRANSACTION", "MOVE");
        {
          memcpy (b_41 + 27, "INVALID CUSTOMER NO      ", 25);
        }
        /* inventory.cbl:199: PERFORM */
        cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 199, "MAIN SECTION", "031-PROCESS-TRANSACTION", "PERFORM");
        {
          /* PERFORM 040-LOG-ERROR */
          frame_ptr++;
          if (unlikely(frame_ptr == frame_overflow))
              cob_fatal_error (COB_FERROR_STACK);
          frame_ptr->perform_through = 11;
          frame_ptr->return_address = &&l_38;
          goto l_11;
          l_38:
          frame_ptr--;
        }
      }
    else
      {
        /* inventory.cbl:201: PERFORM */
        cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 201, "MAIN SECTION", "031-PROCESS-TRANSACTION", "PERFORM");
        {
          /* PERFORM 033-ITEM-NO-SEARCH */
          frame_ptr++;
          if (unlikely(frame_ptr == frame_overflow))
              cob_fatal_error (COB_FERROR_STACK);
          frame_ptr->perform_through = 10;
          frame_ptr->return_address = &&l_39;
          goto l_10;
          l_39:
          frame_ptr--;
        }
        /* inventory.cbl:202: IF */
        cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 202, "MAIN SECTION", "031-PROCESS-TRANSACTION", "IF");
        {
          if (((int)(int)(*(b_63 + 4) - 78) == 0))
            {
              /* inventory.cbl:203: MOVE */
              cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 203, "MAIN SECTION", "031-PROCESS-TRANSACTION", "MOVE");
              {
                memcpy (b_41 + 27, "INVALID PRODUCT NO       ", 25);
              }
              /* inventory.cbl:204: PERFORM */
              cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 204, "MAIN SECTION", "031-PROCESS-TRANSACTION", "PERFORM");
              {
                /* PERFORM 040-LOG-ERROR */
                frame_ptr++;
                if (unlikely(frame_ptr == frame_overflow))
                    cob_fatal_error (COB_FERROR_STACK);
                frame_ptr->perform_through = 11;
                frame_ptr->return_address = &&l_40;
                goto l_11;
                l_40:
                frame_ptr--;
              }
            }
          else
            {
              /* inventory.cbl:206: PERFORM */
              cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 206, "MAIN SECTION", "031-PROCESS-TRANSACTION", "PERFORM");
              {
                /* PERFORM 050-COMPUTE-TRANSACTION */
                frame_ptr++;
                if (unlikely(frame_ptr == frame_overflow))
                    cob_fatal_error (COB_FERROR_STACK);
                frame_ptr->perform_through = 12;
                frame_ptr->return_address = &&l_41;
                goto l_12;
                l_41:
                frame_ptr--;
              }
            }
        }
      }
  }

  if (frame_ptr->perform_through == 8)
    goto *frame_ptr->return_address;

  /* 032-CUST-NO-SEARCH */

  l_9:;
  fputs ("PROGRAM-ID: NKU CSC407 OLDIE ASSIGNMENT: 032-CUST-NO-SEARCH\n", stderr);
  fflush (stderr);
  /* inventory.cbl:211: MOVE */
  cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 211, "MAIN SECTION", "032-CUST-NO-SEARCH", "MOVE");
  {
    *(b_63 + 3) = 78;
  }
  /* inventory.cbl:212: SET */
  cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 212, "MAIN SECTION", "032-CUST-NO-SEARCH", "SET");
  {
    (*(int *) (b_79)) = 1;
  }
  /* inventory.cbl:213: SEARCH */
  cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 213, "MAIN SECTION", "032-CUST-NO-SEARCH", "SEARCH");
  {
    while (1)
      {
        if ((*(int *) (b_79)) > 10)
          {
            break;
          }
        if (((int)cob_cmp (         ({
        cob_check_subscript ((*(int *) (b_79)), 1, 10, "WS-CUST-NO");
(f0.size = 5, f0.data = b_77 + 81 * ((*(int *) (b_79)) - 1), f0.attr = &a_7, &f0); }), &f_25) == 0))
          {
            /* inventory.cbl:215: MOVE */
            cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 215, "MAIN SECTION", "032-CUST-NO-SEARCH", "MOVE");
            {
              *(b_63 + 3) = 89;
            }
          }
        else
          {
            (*(int *) (b_79))++;
            continue;
          }
        break;
      }
  }

  if (frame_ptr->perform_through == 9)
    goto *frame_ptr->return_address;

  /* 033-ITEM-NO-SEARCH */

  l_10:;
  fputs ("PROGRAM-ID: NKU CSC407 OLDIE ASSIGNMENT: 033-ITEM-NO-SEARCH\n", stderr);
  fflush (stderr);
  /* inventory.cbl:219: MOVE */
  cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 219, "MAIN SECTION", "033-ITEM-NO-SEARCH", "MOVE");
  {
    *(b_63 + 4) = 78;
  }
  /* inventory.cbl:220: SET */
  cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 220, "MAIN SECTION", "033-ITEM-NO-SEARCH", "SET");
  {
    (*(int *) (b_71)) = 1;
  }
  /* inventory.cbl:221: SEARCH */
  cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 221, "MAIN SECTION", "033-ITEM-NO-SEARCH", "SEARCH");
  {
    while (1)
      {
        if ((*(int *) (b_71)) > 24)
          {
            break;
          }
        if (((int)cob_cmp (         ({
        cob_check_subscript ((*(int *) (b_71)), 1, 24, "WS-INV-ITEM-NO");
(f0.size = 6, f0.data = b_69 + 39 * ((*(int *) (b_71)) - 1), f0.attr = &a_1, &f0); }), &f_27) == 0))
          {
            /* inventory.cbl:223: MOVE */
            cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 223, "MAIN SECTION", "033-ITEM-NO-SEARCH", "MOVE");
            {
              *(b_63 + 4) = 89;
            }
          }
        else
          {
            (*(int *) (b_71))++;
            continue;
          }
        break;
      }
  }

  if (frame_ptr->perform_through == 10)
    goto *frame_ptr->return_address;

  /* 040-LOG-ERROR */

  l_11:;
  fputs ("PROGRAM-ID: NKU CSC407 OLDIE ASSIGNMENT: 040-LOG-ERROR\n", stderr);
  fflush (stderr);
  /* inventory.cbl:227: MOVE */
  cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 227, "MAIN SECTION", "040-LOG-ERROR", "MOVE");
  {
    cob_move (&f_25, &f_34);
  }
  /* inventory.cbl:228: MOVE */
  cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 228, "MAIN SECTION", "040-LOG-ERROR", "MOVE");
  {
    memcpy (b_41 + 10, b_32 + 10, 6);
  }
  /* inventory.cbl:229: MOVE */
  cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 229, "MAIN SECTION", "040-LOG-ERROR", "MOVE");
  {
    *(b_41 + 21) = *(b_32 + 22);
  }
  /* inventory.cbl:230: WRITE */
  cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 230, "MAIN SECTION", "040-LOG-ERROR", "WRITE");
  cob_exception_code = 0;
  {
    cob_write (h_ERROR_FILE, &f_33, 2162689, NULL);
  }
  if (unlikely(cob_exception_code != 0))
    {
      /* PERFORM Default Error Handler */
      frame_ptr++;
      if (unlikely(frame_ptr == frame_overflow))
          cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 1;
      frame_ptr->return_address = &&l_42;
      goto l_1;
      l_42:
      frame_ptr--;
    }

  if (frame_ptr->perform_through == 11)
    goto *frame_ptr->return_address;

  /* 050-COMPUTE-TRANSACTION */

  l_12:;
  fputs ("PROGRAM-ID: NKU CSC407 OLDIE ASSIGNMENT: 050-COMPUTE-TRANSACTION\n", stderr);
  fflush (stderr);
  /* inventory.cbl:233: MULTIPLY */
  cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 233, "MAIN SECTION", "050-COMPUTE-TRANSACTION", "MULTIPLY");
  {
    {
      {
        cob_check_numeric (&f_29, "TRANS-QTY-ORD");
        cob_decimal_set_uint (&d0, cob_get_numdisp (b_32 + 22, 1));
        cob_check_numeric (         ({
        cob_check_subscript ((*(int *) (b_71)), 1, 24, "WS-INV-PRICE");
(f0.size = 4, f0.data = b_69 + 35 + 39 * ((*(int *) (b_71)) - 1), f0.attr = &a_6, &f0); }), "WS-INV-PRICE");
        cob_decimal_set_field (&d1,          ({
        cob_check_subscript ((*(int *) (b_71)), 1, 24, "WS-INV-PRICE");
(f0.size = 4, f0.data = b_69 + 35 + 39 * ((*(int *) (b_71)) - 1), f0.attr = &a_6, &f0); }));
        cob_decimal_mul (&d0, &d1);
        cob_decimal_get_field (&d0, &f_50, 2);
      }
    }
  }
  /* inventory.cbl:234: PERFORM */
  cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 234, "MAIN SECTION", "050-COMPUTE-TRANSACTION", "PERFORM");
  {
    /* PERFORM 051-CALCULATE-DISCOUNT */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 13;
    frame_ptr->return_address = &&l_43;
    goto l_13;
    l_43:
    frame_ptr--;
  }
  /* inventory.cbl:235: SUBTRACT */
  cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 235, "MAIN SECTION", "050-COMPUTE-TRANSACTION", "SUBTRACT");
  {
    {
      {
        cob_check_numeric (&f_50, "TP-GROSS-COST");
        cob_decimal_set_field (&d0, &f_50);
        cob_check_numeric (&f_52, "TP-DISCOUNT");
        cob_decimal_set_field (&d1, &f_52);
        cob_decimal_sub (&d0, &d1);
        cob_decimal_get_field (&d0, &f_54, 2);
      }
    }
  }
  /* inventory.cbl:236: PERFORM */
  cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 236, "MAIN SECTION", "050-COMPUTE-TRANSACTION", "PERFORM");
  {
    /* PERFORM 052-UPDATE-CUST-TABLE */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 14;
    frame_ptr->return_address = &&l_44;
    goto l_14;
    l_44:
    frame_ptr--;
  }
  /* inventory.cbl:237: PERFORM */
  cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 237, "MAIN SECTION", "050-COMPUTE-TRANSACTION", "PERFORM");
  {
    /* PERFORM 053-UPDATE-INV-TABLE */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 15;
    frame_ptr->return_address = &&l_45;
    goto l_15;
    l_45:
    frame_ptr--;
  }
  /* inventory.cbl:238: PERFORM */
  cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 238, "MAIN SECTION", "050-COMPUTE-TRANSACTION", "PERFORM");
  {
    /* PERFORM 070-CHECK-REORDER */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 16;
    frame_ptr->return_address = &&l_46;
    goto l_16;
    l_46:
    frame_ptr--;
  }
  /* inventory.cbl:239: PERFORM */
  cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 239, "MAIN SECTION", "050-COMPUTE-TRANSACTION", "PERFORM");
  {
    /* PERFORM 080-LOG-TRANS */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 17;
    frame_ptr->return_address = &&l_47;
    goto l_17;
    l_47:
    frame_ptr--;
  }

  if (frame_ptr->perform_through == 12)
    goto *frame_ptr->return_address;

  /* 051-CALCULATE-DISCOUNT */

  l_13:;
  fputs ("PROGRAM-ID: NKU CSC407 OLDIE ASSIGNMENT: 051-CALCULATE-DISCOUNT\n", stderr);
  fflush (stderr);
  /* inventory.cbl:243: IF */
  cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 243, "MAIN SECTION", "051-CALCULATE-DISCOUNT", "IF");
  {
    if (((int)(int)(*(b_32 + 28) - 65) == 0))
      {
        /* inventory.cbl:244: MULTIPLY */
        cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 244, "MAIN SECTION", "051-CALCULATE-DISCOUNT", "MULTIPLY");
        {
          {
            {
              cob_check_numeric (&f_50, "TP-GROSS-COST");
              cob_decimal_set_field (&d0, &f_50);
              cob_decimal_set_field (&d1, &c_8);
              cob_decimal_mul (&d0, &d1);
              cob_decimal_get_field (&d0, &f_52, 2);
            }
          }
        }
      }
    else
      {
        /* inventory.cbl:245: IF */
        cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 245, "MAIN SECTION", "051-CALCULATE-DISCOUNT", "IF");
        {
          if (((int)(int)(*(b_32 + 28) - 66) == 0))
            {
              /* inventory.cbl:246: MULTIPLY */
              cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 246, "MAIN SECTION", "051-CALCULATE-DISCOUNT", "MULTIPLY");
              {
                {
                  {
                    cob_check_numeric (&f_50, "TP-GROSS-COST");
                    cob_decimal_set_field (&d0, &f_50);
                    cob_decimal_set_field (&d1, &c_9);
                    cob_decimal_mul (&d0, &d1);
                    cob_decimal_get_field (&d0, &f_52, 2);
                  }
                }
              }
            }
          else
            {
              /* inventory.cbl:247: IF */
              cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 247, "MAIN SECTION", "051-CALCULATE-DISCOUNT", "IF");
              {
                if (((int)(int)(*(b_32 + 28) - 67) == 0))
                  {
                    /* inventory.cbl:248: MULTIPLY */
                    cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 248, "MAIN SECTION", "051-CALCULATE-DISCOUNT", "MULTIPLY");
                    {
                      {
                        {
                          cob_check_numeric (&f_50, "TP-GROSS-COST");
                          cob_decimal_set_field (&d0, &f_50);
                          cob_decimal_set_field (&d1, &c_10);
                          cob_decimal_mul (&d0, &d1);
                          cob_decimal_get_field (&d0, &f_52, 2);
                        }
                      }
                    }
                  }
                else
                  {
                    /* inventory.cbl:249: IF */
                    cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 249, "MAIN SECTION", "051-CALCULATE-DISCOUNT", "IF");
                    {
                      if (((int)(int)(*(b_32 + 28) - 68) == 0))
                        {
                          /* inventory.cbl:250: IF */
                          cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 250, "MAIN SECTION", "051-CALCULATE-DISCOUNT", "IF");
                          {
                            if (((int)cob_cmp_numdisp (b_32 + 22, 1, 2) >  0))
                              {
                                /* inventory.cbl:251: SET */
                                cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 251, "MAIN SECTION", "051-CALCULATE-DISCOUNT", "SET");
                                {
                                  cob_move (                                   ({
                                  cob_check_subscript ((*(int *) (b_71)), 1, 24, "WS-INV-PRICE");
(f0.size = 4, f0.data = b_69 + 35 + 39 * ((*(int *) (b_71)) - 1), f0.attr = &a_6, &f0); }), &f_52);
                                }
                              }
                          }
                        }
                      else
                        {
                          /* inventory.cbl:253: IF */
                          cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 253, "MAIN SECTION", "051-CALCULATE-DISCOUNT", "IF");
                          {
                            if (((int)(int)(*(b_32 + 28) - 69) == 0))
                              {
                                /* inventory.cbl:254: MULTIPLY */
                                cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 254, "MAIN SECTION", "051-CALCULATE-DISCOUNT", "MULTIPLY");
                                {
                                  {
                                    {
                                      cob_check_numeric (&f_50, "TP-GROSS-COST");
                                      cob_decimal_set_field (&d0, &f_50);
                                      cob_decimal_set_field (&d1, &c_11);
                                      cob_decimal_mul (&d0, &d1);
                                      cob_decimal_get_field (&d0, &f_52, 2);
                                    }
                                  }
                                }
                              }
                            else
                              {
                                /* inventory.cbl:256: MOVE */
                                cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 256, "MAIN SECTION", "051-CALCULATE-DISCOUNT", "MOVE");
                                {
                                  cob_move (&c_12, &f_52);
                                }
                              }
                          }
                        }
                    }
                  }
              }
            }
        }
      }
  }

  if (frame_ptr->perform_through == 13)
    goto *frame_ptr->return_address;

  /* 052-UPDATE-CUST-TABLE */

  l_14:;
  fputs ("PROGRAM-ID: NKU CSC407 OLDIE ASSIGNMENT: 052-UPDATE-CUST-TABLE\n", stderr);
  fflush (stderr);
  /* inventory.cbl:260: ADD */
  cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 260, "MAIN SECTION", "052-UPDATE-CUST-TABLE", "ADD");
  {
    {
      {
        cob_check_numeric (&f_54, "TP-NETCOST");
        cob_decimal_set_field (&d0, &f_54);
        cob_check_numeric (         ({
        cob_check_subscript ((*(int *) (b_79)), 1, 10, "WS-CUST-PAST-DUE");
(f0.size = 5, f0.data = b_77 + 76 + 81 * ((*(int *) (b_79)) - 1), f0.attr = &a_9, &f0); }), "WS-CUST-PAST-DUE");
        cob_decimal_set_field (&d1,          ({
        cob_check_subscript ((*(int *) (b_79)), 1, 10, "WS-CUST-PAST-DUE");
(f0.size = 5, f0.data = b_77 + 76 + 81 * ((*(int *) (b_79)) - 1), f0.attr = &a_9, &f0); }));
        cob_decimal_add (&d0, &d1);
        cob_decimal_get_field (&d0,          ({
        cob_check_subscript ((*(int *) (b_79)), 1, 10, "WS-CUST-PAST-DUE");
(f0.size = 5, f0.data = b_77 + 76 + 81 * ((*(int *) (b_79)) - 1), f0.attr = &a_9, &f0); }), 2);
      }
    }
  }

  if (frame_ptr->perform_through == 14)
    goto *frame_ptr->return_address;

  /* 053-UPDATE-INV-TABLE */

  l_15:;
  fputs ("PROGRAM-ID: NKU CSC407 OLDIE ASSIGNMENT: 053-UPDATE-INV-TABLE\n", stderr);
  fflush (stderr);
  /* inventory.cbl:264: SUBTRACT */
  cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 264, "MAIN SECTION", "053-UPDATE-INV-TABLE", "SUBTRACT");
  {
    {
      {
        cob_check_numeric (         ({
        cob_check_subscript ((*(int *) (b_71)), 1, 24, "WS-INV-QTY");
(f0.size = 2, f0.data = b_69 + 31 + 39 * ((*(int *) (b_71)) - 1), f0.attr = &a_4, &f0); }), "WS-INV-QTY");
        cob_decimal_set_uint (&d0, cob_get_numdisp (b_69 + 31 + 39 * ((*(int *) (b_71)) - 1), 2));
        cob_check_numeric (&f_29, "TRANS-QTY-ORD");
        cob_decimal_set_uint (&d1, cob_get_numdisp (b_32 + 22, 1));
        cob_decimal_sub (&d0, &d1);
        cob_decimal_get_field (&d0,          ({
        cob_check_subscript ((*(int *) (b_71)), 1, 24, "WS-INV-QTY");
(f0.size = 2, f0.data = b_69 + 31 + 39 * ((*(int *) (b_71)) - 1), f0.attr = &a_4, &f0); }), 2);
      }
    }
  }

  if (frame_ptr->perform_through == 15)
    goto *frame_ptr->return_address;

  /* 070-CHECK-REORDER */

  l_16:;
  fputs ("PROGRAM-ID: NKU CSC407 OLDIE ASSIGNMENT: 070-CHECK-REORDER\n", stderr);
  fflush (stderr);
  /* inventory.cbl:268: MOVE */
  cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 268, "MAIN SECTION", "070-CHECK-REORDER", "MOVE");
  {
    memset (b_62, 32, 14);
  }
  /* inventory.cbl:269: MOVE */
  cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 269, "MAIN SECTION", "070-CHECK-REORDER", "MOVE");
  {
    memset (b_62 + 12, 48, 2);
  }
  /* inventory.cbl:270: IF */
  cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 270, "MAIN SECTION", "070-CHECK-REORDER", "IF");
  {
    if (((int)memcmp (b_69 + 31 + 39 * ((*(int *) (b_71)) - 1), b_69 + 33 + 39 * ((*(int *) (b_71)) - 1), 2) <= 0))
      {
        /* inventory.cbl:271: DISPLAY */
        cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 271, "MAIN SECTION", "070-CHECK-REORDER", "DISPLAY");
        {
          cob_display (0, 1, 1, &c_13);
        }
        /* inventory.cbl:272: DISPLAY */
        cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 272, "MAIN SECTION", "070-CHECK-REORDER", "DISPLAY");
        {
          cob_display (0, 1, 1,            ({
          cob_check_subscript ((*(int *) (b_71)), 1, 24, "WS-INV-QTY");
(f0.size = 2, f0.data = b_69 + 31 + 39 * ((*(int *) (b_71)) - 1), f0.attr = &a_4, &f0); }));
        }
        /* inventory.cbl:273: DISPLAY */
        cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 273, "MAIN SECTION", "070-CHECK-REORDER", "DISPLAY");
        {
          cob_display (0, 1, 1,            ({
          cob_check_subscript ((*(int *) (b_71)), 1, 24, "WS-INV-REORDER-PT");
(f0.size = 2, f0.data = b_69 + 33 + 39 * ((*(int *) (b_71)) - 1), f0.attr = &a_4, &f0); }));
        }
        /* inventory.cbl:274: IF */
        cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 274, "MAIN SECTION", "070-CHECK-REORDER", "IF");
        {
          if (((int)cob_cmp_numdisp (b_69 + 33 + 39 * ((*(int *) (b_71)) - 1), 2, 1) == 0))
            {
              /* inventory.cbl:275: SUBTRACT */
              cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 275, "MAIN SECTION", "070-CHECK-REORDER", "SUBTRACT");
              {
                {
                  {
                    cob_decimal_set_int (&d0, 3);
                    cob_check_numeric (                     ({
                    cob_check_subscript ((*(int *) (b_71)), 1, 24, "WS-INV-QTY");
(f0.size = 2, f0.data = b_69 + 31 + 39 * ((*(int *) (b_71)) - 1), f0.attr = &a_4, &f0); }), "WS-INV-QTY");
                    cob_decimal_set_uint (&d1, cob_get_numdisp (b_69 + 31 + 39 * ((*(int *) (b_71)) - 1), 2));
                    cob_decimal_sub (&d0, &d1);
                    cob_decimal_get_field (&d0, &f_61, 2);
                  }
                }
              }
            }
          else
            {
              /* inventory.cbl:276: IF */
              cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 276, "MAIN SECTION", "070-CHECK-REORDER", "IF");
              {
                if (((int)cob_cmp_numdisp (b_69 + 33 + 39 * ((*(int *) (b_71)) - 1), 2, 6) <  0))
                  {
                    /* inventory.cbl:277: SUBTRACT */
                    cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 277, "MAIN SECTION", "070-CHECK-REORDER", "SUBTRACT");
                    {
                      {
                        {
                          cob_decimal_set_int (&d0, 6);
                          cob_check_numeric (                           ({
                          cob_check_subscript ((*(int *) (b_71)), 1, 24, "WS-INV-QTY");
(f0.size = 2, f0.data = b_69 + 31 + 39 * ((*(int *) (b_71)) - 1), f0.attr = &a_4, &f0); }), "WS-INV-QTY");
                          cob_decimal_set_uint (&d1, cob_get_numdisp (b_69 + 31 + 39 * ((*(int *) (b_71)) - 1), 2));
                          cob_decimal_sub (&d0, &d1);
                          cob_decimal_get_field (&d0, &f_61, 2);
                        }
                      }
                    }
                  }
                else
                  {
                    /* inventory.cbl:278: IF */
                    cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 278, "MAIN SECTION", "070-CHECK-REORDER", "IF");
                    {
                      if (((int)cob_cmp_numdisp (b_69 + 33 + 39 * ((*(int *) (b_71)) - 1), 2, 11) <  0))
                        {
                          /* inventory.cbl:279: SUBTRACT */
                          cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 279, "MAIN SECTION", "070-CHECK-REORDER", "SUBTRACT");
                          {
                            {
                              {
                                cob_decimal_set_int (&d0, 12);
                                cob_check_numeric (                                 ({
                                cob_check_subscript ((*(int *) (b_71)), 1, 24, "WS-INV-QTY");
(f0.size = 2, f0.data = b_69 + 31 + 39 * ((*(int *) (b_71)) - 1), f0.attr = &a_4, &f0); }), "WS-INV-QTY");
                                cob_decimal_set_uint (&d1, cob_get_numdisp (b_69 + 31 + 39 * ((*(int *) (b_71)) - 1), 2));
                                cob_decimal_sub (&d0, &d1);
                                cob_decimal_get_field (&d0, &f_61, 2);
                              }
                            }
                          }
                        }
                      else
                        {
                          /* inventory.cbl:280: IF */
                          cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 280, "MAIN SECTION", "070-CHECK-REORDER", "IF");
                          {
                            if (((int)cob_cmp_numdisp (b_69 + 33 + 39 * ((*(int *) (b_71)) - 1), 2, 21) <  0))
                              {
                                /* inventory.cbl:281: SUBTRACT */
                                cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 281, "MAIN SECTION", "070-CHECK-REORDER", "SUBTRACT");
                                {
                                  {
                                    {
                                      cob_decimal_set_int (&d0, 25);
                                      cob_check_numeric (                                       ({
                                      cob_check_subscript ((*(int *) (b_71)), 1, 24, "WS-INV-QTY");
(f0.size = 2, f0.data = b_69 + 31 + 39 * ((*(int *) (b_71)) - 1), f0.attr = &a_4, &f0); }), "WS-INV-QTY");
                                      cob_decimal_set_uint (&d1, cob_get_numdisp (b_69 + 31 + 39 * ((*(int *) (b_71)) - 1), 2));
                                      cob_decimal_sub (&d0, &d1);
                                      cob_decimal_get_field (&d0, &f_61, 2);
                                    }
                                  }
                                }
                              }
                            else
                              {
                                /* inventory.cbl:283: SUBTRACT */
                                cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 283, "MAIN SECTION", "070-CHECK-REORDER", "SUBTRACT");
                                {
                                  {
                                    {
                                      cob_decimal_set_int (&d0, 30);
                                      cob_check_numeric (                                       ({
                                      cob_check_subscript ((*(int *) (b_71)), 1, 24, "WS-INV-QTY");
(f0.size = 2, f0.data = b_69 + 31 + 39 * ((*(int *) (b_71)) - 1), f0.attr = &a_4, &f0); }), "WS-INV-QTY");
                                      cob_decimal_set_uint (&d1, cob_get_numdisp (b_69 + 31 + 39 * ((*(int *) (b_71)) - 1), 2));
                                      cob_decimal_sub (&d0, &d1);
                                      cob_decimal_get_field (&d0, &f_61, 2);
                                    }
                                  }
                                }
                              }
                          }
                          /* inventory.cbl:285: DISPLAY */
                          cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 285, "MAIN SECTION", "070-CHECK-REORDER", "DISPLAY");
                          {
                            cob_display (0, 1, 1, &f_61);
                          }
                          /* inventory.cbl:286: DISPLAY */
                          cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 286, "MAIN SECTION", "070-CHECK-REORDER", "DISPLAY");
                          {
                            cob_display (0, 1, 1, &c_14);
                          }
                          /* inventory.cbl:287: MOVE */
                          cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 287, "MAIN SECTION", "070-CHECK-REORDER", "MOVE");
                          {
                            cob_move (                             ({
                            cob_check_subscript ((*(int *) (b_71)), 1, 24, "WS-INV-ITEM-NO");
(f0.size = 6, f0.data = b_69 + 39 * ((*(int *) (b_71)) - 1), f0.attr = &a_1, &f0); }), &f_59);
                          }
                          /* inventory.cbl:288: ADD */
                          cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 288, "MAIN SECTION", "070-CHECK-REORDER", "ADD");
                          {
                            {
                              {
                                cob_check_numeric (&f_61, "ORDER-QTY");
                                cob_decimal_set_uint (&d0, cob_get_numdisp (b_62 + 12, 2));
                                cob_check_numeric (                                 ({
                                cob_check_subscript ((*(int *) (b_71)), 1, 24, "WS-INV-QTY");
(f0.size = 2, f0.data = b_69 + 31 + 39 * ((*(int *) (b_71)) - 1), f0.attr = &a_4, &f0); }), "WS-INV-QTY");
                                cob_decimal_set_uint (&d1, cob_get_numdisp (b_69 + 31 + 39 * ((*(int *) (b_71)) - 1), 2));
                                cob_decimal_add (&d0, &d1);
                                cob_decimal_get_field (&d0,                                  ({
                                cob_check_subscript ((*(int *) (b_71)), 1, 24, "WS-INV-QTY");
(f0.size = 2, f0.data = b_69 + 31 + 39 * ((*(int *) (b_71)) - 1), f0.attr = &a_4, &f0); }), 2);
                              }
                            }
                          }
                          /* inventory.cbl:289: WRITE */
                          cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 289, "MAIN SECTION", "070-CHECK-REORDER", "WRITE");
                          cob_exception_code = 0;
                          {
                            cob_write (h_INV_ORDER_FILE, &f_58, 2162689, NULL);
                          }
                          if (unlikely(cob_exception_code != 0))
                            {
                              /* PERFORM Default Error Handler */
                              frame_ptr++;
                              if (unlikely(frame_ptr == frame_overflow))
                                  cob_fatal_error (COB_FERROR_STACK);
                              frame_ptr->perform_through = 1;
                              frame_ptr->return_address = &&l_48;
                              goto l_1;
                              l_48:
                              frame_ptr--;
                            }
                        }
                    }
                  }
              }
            }
        }
      }
  }

  if (frame_ptr->perform_through == 16)
    goto *frame_ptr->return_address;

  /* 080-LOG-TRANS */

  l_17:;
  fputs ("PROGRAM-ID: NKU CSC407 OLDIE ASSIGNMENT: 080-LOG-TRANS\n", stderr);
  fflush (stderr);
  /* inventory.cbl:293: MOVE */
  cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 293, "MAIN SECTION", "080-LOG-TRANS", "MOVE");
  {
    memset (b_57, 32, 142);
  }
  /* inventory.cbl:294: MOVE */
  cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 294, "MAIN SECTION", "080-LOG-TRANS", "MOVE");
  {
    cob_move (     ({
    cob_check_subscript ((*(int *) (b_79)), 1, 10, "WS-CUST-NAME");
(f0.size = 23, f0.data = b_77 + 5 + 81 * ((*(int *) (b_79)) - 1), f0.attr = &a_1, &f0); }), &f_43);
  }
  /* inventory.cbl:295: MOVE */
  cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 295, "MAIN SECTION", "080-LOG-TRANS", "MOVE");
  {
    cob_move (     ({
    cob_check_subscript ((*(int *) (b_79)), 1, 10, "WS-CUST-STREET");
(f0.size = 23, f0.data = b_77 + 28 + 81 * ((*(int *) (b_79)) - 1), f0.attr = &a_1, &f0); }), &f_44);
  }
  /* inventory.cbl:296: MOVE */
  cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 296, "MAIN SECTION", "080-LOG-TRANS", "MOVE");
  {
    cob_move (     ({
    cob_check_subscript ((*(int *) (b_79)), 1, 10, "WS-CUST-CITY");
(f0.size = 13, f0.data = b_77 + 51 + 81 * ((*(int *) (b_79)) - 1), f0.attr = &a_1, &f0); }), &f_45);
  }
  /* inventory.cbl:297: MOVE */
  cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 297, "MAIN SECTION", "080-LOG-TRANS", "MOVE");
  {
    cob_move (     ({
    cob_check_subscript ((*(int *) (b_79)), 1, 10, "WS-CUST-REGION");
(f0.size = 12, f0.data = b_77 + 64 + 81 * ((*(int *) (b_79)) - 1), f0.attr = &a_1, &f0); }), &f_46);
  }
  /* inventory.cbl:298: MOVE */
  cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 298, "MAIN SECTION", "080-LOG-TRANS", "MOVE");
  {
    cob_move (     ({
    cob_check_subscript ((*(int *) (b_71)), 1, 24, "WS-INV-ITEM-NAME");
(f0.size = 25, f0.data = b_69 + 6 + 39 * ((*(int *) (b_71)) - 1), f0.attr = &a_1, &f0); }), &f_47);
  }
  /* inventory.cbl:299: MOVE */
  cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 299, "MAIN SECTION", "080-LOG-TRANS", "MOVE");
  {
    cob_move (     ({
    cob_check_subscript ((*(int *) (b_71)), 1, 24, "WS-INV-QTY");
(f0.size = 2, f0.data = b_69 + 31 + 39 * ((*(int *) (b_71)) - 1), f0.attr = &a_4, &f0); }), &f_48);
  }
  /* inventory.cbl:300: MOVE */
  cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 300, "MAIN SECTION", "080-LOG-TRANS", "MOVE");
  {
    cob_move (     ({
    cob_check_subscript ((*(int *) (b_79)), 1, 10, "WS-CUST-PAST-DUE");
(f0.size = 5, f0.data = b_77 + 76 + 81 * ((*(int *) (b_79)) - 1), f0.attr = &a_9, &f0); }), &f_56);
  }
  /* inventory.cbl:301: WRITE */
  cob_set_location ("NKU CSC407 OLDIE ASSIGNMENT", "inventory.cbl", 301, "MAIN SECTION", "080-LOG-TRANS", "WRITE");
  cob_exception_code = 0;
  {
    cob_write (h_TRANS_OUTPUT_FILE, &f_42, 2162689, NULL);
  }
  if (unlikely(cob_exception_code != 0))
    {
      /* PERFORM Default Error Handler */
      frame_ptr++;
      if (unlikely(frame_ptr == frame_overflow))
          cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 1;
      frame_ptr->return_address = &&l_49;
      goto l_1;
      l_49:
      frame_ptr--;
    }

  if (frame_ptr->perform_through == 17)
    goto *frame_ptr->return_address;

  /* Program exit */

  /* Pop module stack */
  cob_current_module = cob_current_module->next;

  cob_reset_trace ();

  /* Program return */
  return (*(int *) (b_1));


  /* Default Error Handler */

  l_1:;
  fputs ("PROGRAM-ID: NKU CSC407 OLDIE ASSIGNMENT: Default Error Handler\n", stderr);
  fflush (stderr);

  if (!(cob_error_file->flag_select_features & COB_SELECT_FILE_STATUS)) {
  	cob_default_error_handle ();
  	cob_stop_run (1);
  }

  if (frame_ptr->perform_through == 1)
    goto *frame_ptr->return_address;

  cob_fatal_error (COB_FERROR_CODEGEN);

}

/* End functions */

